### ISSUE TITLE
Reported heading is a bit weird 

### ISSUE THREAD

**Issue by pierr3** [ogruetzmann/ModeS#4] opened 2016-08-29 21:26 UTC
The reported heading from the aircraft is not displayed properly in EuroScope, see capture (Last item is heading)

https://s3.eu-central-1.amazonaws.com/pithos/ShareX/2016/08/EuroScope_2016-08-29_23-25-41.png

**Comment by ogruetzmann** [comment] 2016-08-29 21:56
That looks strange, indeed. Will have a look on wednesday.

**Comment by ogruetzmann** [comment] 2016-08-31 10:35
@pierr3 I am able to reproduce this, it's reported heading + 360. Strange enough, that's the value I get from GetReportedHeading().
Are you using ES Beta or the public release version? I ask because I tested this once in an earlier beta and I believe it was working fine there.
I will take this to the ES Beta forum.

**Comment by pierr3** [comment] 2016-08-31 11:04
Yes, I'm using the latest EuroScope beta, but somehow it works fine with
vSMR, which also uses this value to display the "primary target" on the
radar pointed the correct way.

2016-08-31 12:35 GMT+02:00 ogruetzmann notifications@github.com:

**Comment by ogruetzmann** [comment] 2016-08-31 11:13
Did you check the actual return value there? Depending on what function you use, it will work just fine. I used GeographicLib in another plugin, and it doesn't matter if the value is 270 or 630, the result is the same.
I just checked in the public release version, the value is fine there. In the beta, 
`int hdg = GetReportedHeading()`
leaves me with heading + 360 (I checked this via debug session).

To me it looks like Gergely has to fix it. If I do it, I'll either have to put in a switch, or I'll break it for public release users.

**Comment by ogruetzmann** [comment] 2016-08-31 11:19
Here's the result from the public release (third row):
![hdg](https://cloud.githubusercontent.com/assets/3863353/18126855/6a9b97ba-6f7d-11e6-98ae-5a0fe3d34452.PNG)

**Comment by pierr3** [comment] 2016-08-31 11:20
Maybe just do (x + 360) % 360 ? It'll work for both public and beta.

**Comment by ogruetzmann** [comment] 2016-08-31 11:31
Good idea. Never thought about using the modulo operator this way. I'll do this. :)

**Closed as completed by ogruetzmann** 2016-08-31 11:31 UTC

**Comment by ogruetzmann** [comment] 2016-08-31 11:40
Looks fine:

[ModeS-static.zip](https://github.com/ogruetzmann/ModeS/files/447086/ModeS-static.zip)
